fix(accelerate/nodejs-tracing): remove middleware instrumentation (#5977)
Fixes a TypeScript error:

```
      index.test.ts:36:52 - error TS2353: Object literal may only specify known properties, and 'middleware' does not exist in type 'Config'.
  
      36     instrumentations: [new PrismaInstrumentation({ middleware: true })],
                                                            ~~~~~~~~~~
```