ci(check-update): pin pnpm to v8
Because we still run on Node.js v16, we should later upgrade everything to v18 and unpin pnpm.

Currently fails with
https://github.com/prisma/ecosystem-tests/actions/runs/8797597444/job/24142829992
```
+ npm show prisma@5.13.0-dev.37 version
+ NEW_VERSION=5.13.0-dev.37
+ echo 5.13.0-dev.37
+ corepack enable
+ pwd
+ pnpm -rc --parallel exec /home/runner/work/ecosystem-tests/ecosystem-tests/scripts/update-version.sh 5.13.0-dev.37
ERROR: This version of pnpm requires at least Node.js v18.12
The current version of Node.js is v16.20.2
Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```